#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"


theme="material-design"
baseurl = "http://shiny2.alfredlin.com/"
languageCode = "en-us"
title = "Alfred's Analysis"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
#disqusShortname = "Your Disqus Name" # optional
copyright = "© 2018 Copyright"

[params]
  description = "Where I put all my R code!" # optional
  github = "alflin" # optional
  linkedin = "alfredelin" # optional
  #headerCover = "images/headerCover.png" # optional
  #footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
